name: Update Nightly 

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.6

      - run: bun install --frozen-lockfile

      - name: Generate files 
        run: bun run start

      - name: Update Nightly
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          name: Nightly Release 
          tag: Nightly
          commit: main
          artifacts: "dist/*.json"
          draft: false
          prerelease: true
          replacesArtifacts: true
          allowUpdates: true
          generateReleaseNotes: true
